-- Generated by tools/compose_editor_shared_forward.py; source hashes are locked.
-- Only the isolated edoc namespace changes. Do not send official exchanges.
begin;
select pg_catalog.pg_advisory_xact_lock(1788103601, 20260911);
do $preflight$
begin
  if pg_catalog.to_regclass('edoc_private.shared_project_migration_ledger') is null
     or pg_catalog.to_regclass('edoc.official_documents') is null
     or not exists(select 1 from pg_catalog.pg_roles where rolname='edoc_backend' and not rolbypassrls)
     or not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260908135911_compose_electronic_output_dispatch_date.sql') then
    raise exception 'shared_compose_editor_preflight_failed';
  end if;
end $preflight$;

do $forward_0$
begin
  if exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260911133144_compose_resilience_drafts_revision.sql'
    and (source_sha256 <> '2e0a814e487e9100e80065b7eb30c0d1815a189d3620afe2b24aff621c2f9b27' or transformed_sha256 <> 'eae4a3ec5a1f2287874c75b46c3706680081b680a7c7ab2aa222768b4e3d531d')) then
    raise exception 'shared_compose_editor_source_hash_mismatch';
  end if;
  if not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260911133144_compose_resilience_drafts_revision.sql') then
    execute $source_0$
-- Incomplete cloud snapshots are private to their applicant and company.
create table if not exists edoc.official_document_compose_drafts (
  id text primary key,
  company_id text not null references edoc.companies(id),
  applicant_id text not null references edoc.users(id),
  revision integer not null default 1 check (revision > 0),
  snapshot_json jsonb not null check (jsonb_typeof(snapshot_json) = 'object'),
  snapshot_hash text not null,
  archived boolean not null default false,
  created_at text not null,
  updated_at text not null
);
create index if not exists idx_compose_draft_owner on edoc.official_document_compose_drafts(applicant_id, company_id, archived, updated_at desc);
alter table edoc.official_document_compose_drafts enable row level security;
revoke all on edoc.official_document_compose_drafts from public, anon, authenticated;
grant select, insert, update, delete on edoc.official_document_compose_drafts to edoc_backend;

create or replace function edoc.edoc_save_compose_draft(
  p_id text, p_applicant_id text, p_company_id text, p_expected_revision integer,
  p_snapshot jsonb, p_hash text, p_archived boolean default false
) returns jsonb language plpgsql security invoker set search_path = '' as $$
declare
  v_row edoc.official_document_compose_drafts%rowtype;
  v_time text := pg_catalog.to_char(pg_catalog.clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS.US');
begin
  if p_expected_revision < 0 or p_expected_revision is null or pg_catalog.jsonb_typeof(p_snapshot) <> 'object'
     or pg_catalog.octet_length(p_snapshot::text) > 250000
     or p_snapshot->>'userId' is distinct from p_applicant_id
     or p_snapshot->>'companyId' is distinct from p_company_id then
    raise exception using errcode = '22023', message = 'compose_draft_snapshot_invalid';
  end if;
  if not exists(select 1 from edoc.users where id=p_applicant_id and company_id=p_company_id) then
    raise exception using errcode = '42501', message = 'compose_draft_scope_forbidden';
  end if;
  if p_expected_revision = 0 then
    insert into edoc.official_document_compose_drafts values(p_id, p_company_id, p_applicant_id, 1, p_snapshot, p_hash, p_archived, v_time, v_time)
    on conflict(id) do nothing;
  end if;
  select * into v_row from edoc.official_document_compose_drafts where id=p_id for update;
  if not found then
    raise exception using errcode = 'PT409', message = 'compose_draft_revision_conflict';
  end if;
  if v_row.applicant_id is distinct from p_applicant_id or v_row.company_id is distinct from p_company_id then
    raise exception using errcode = '42501', message = 'compose_draft_scope_forbidden';
  end if;
  if v_row.snapshot_hash = p_hash and v_row.snapshot_json = p_snapshot and v_row.archived = p_archived then
    return pg_catalog.to_jsonb(v_row);
  end if;
  if v_row.revision <> p_expected_revision then
    raise exception using errcode = 'PT409', message = 'compose_draft_revision_conflict';
  end if;
  update edoc.official_document_compose_drafts set snapshot_json=p_snapshot, snapshot_hash=p_hash,
    revision=revision+1, archived=p_archived, updated_at=v_time where id=p_id returning * into v_row;
  return pg_catalog.to_jsonb(v_row);
end $$;
revoke all on function edoc.edoc_save_compose_draft(text,text,text,integer,jsonb,text,boolean) from public, anon, authenticated;
grant execute on function edoc.edoc_save_compose_draft(text,text,text,integer,jsonb,text,boolean) to edoc_backend;

alter table edoc.official_documents add column if not exists content_revision integer not null default 0;
-- Extend the existing atomic correction RPC, preserving its actor, state, file,
-- number, stamp and audit transaction. The version check runs under its row lock.
do $migration$
declare
  v_proc regprocedure := 'edoc.edoc_apply_official_document_correction(text,text,text,jsonb,text,jsonb,jsonb,text,jsonb,jsonb,text,text,text,text,text,text,jsonb,text,text)'::regprocedure;
  v_sql text;
  v_old text;
begin
  v_sql := pg_catalog.pg_get_functiondef(v_proc);
  v_old := '''workflow_template_key'', ''metadata_json''';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_revision_allowed_keys_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, '''workflow_template_key'', ''metadata_json'', ''_expected_content_revision''');
  v_old := '  select actor.*';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_revision_lock_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, $snippet$
  if p_patch ? '_expected_content_revision' and (p_patch->>'_expected_content_revision')::integer <> v_document.content_revision then
    raise exception using errcode = 'PT409', message = 'compose_content_revision_conflict';
  end if;
  select actor.*
$snippet$);
  v_old := '         workflow_template_key = p_patch->>''workflow_template_key'',';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_revision_write_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, '         content_revision = content_revision + 1,' || chr(10) || v_old);
  execute v_sql;
end $migration$;

do $migration$
declare
  v_sql text := pg_catalog.pg_get_functiondef('edoc.edoc_commit_official_document_submission(jsonb)'::regprocedure);
  v_old text := '  if v_document.updated_at is distinct from v_expected_updated_at then';
begin
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_submit_revision_lock_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, $snippet$
  if p_request ? 'expected_content_revision' and (p_request->>'expected_content_revision')::integer <> v_document.content_revision then
    raise exception using errcode = 'PT409', message = 'compose_content_revision_conflict';
  end if;
  if v_document.updated_at is distinct from v_expected_updated_at then
$snippet$);
  execute v_sql;
end $migration$;
$source_0$;
    insert into edoc_private.shared_project_migration_ledger(file_name,source_sha256,transformed_sha256,bundle_version)
      values('20260911133144_compose_resilience_drafts_revision.sql','2e0a814e487e9100e80065b7eb30c0d1815a189d3620afe2b24aff621c2f9b27','eae4a3ec5a1f2287874c75b46c3706680081b680a7c7ab2aa222768b4e3d531d','shared-project-schema-v1');
  end if;
end $forward_0$;

do $forward_1$
begin
  if exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260911133603_editor_conflict_copy_atomic.sql'
    and (source_sha256 <> 'f5485567cb3ab348cc8f44b408d06d5ab5aa0f56e66d0daf6b840a27e16618b8' or transformed_sha256 <> '909efc2dee65fc2b897f741e3e86f25d580359ee6c8f6cf1eef55346b14daac2')) then
    raise exception 'shared_compose_editor_source_hash_mismatch';
  end if;
  if not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260911133603_editor_conflict_copy_atomic.sql') then
    execute $source_1$
-- Only the authenticated application backend may request this transaction.
-- Source rows stay immutable and new files are document-bound private copies.
CREATE OR REPLACE FUNCTION edoc.edoc_copy_editor_conflict(p_bundle jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, edoc
AS $$
DECLARE
  v_source edoc.official_documents%ROWTYPE;
  v_existing edoc.official_documents%ROWTYPE;
  v_document edoc.official_documents%ROWTYPE;
  v_meta jsonb;
  v_row jsonb;
  v_id text := p_bundle->'document'->>'id';
  v_actor text := p_bundle->>'actor_id';
BEGIN
  IF current_user <> 'edoc_backend' THEN
    RAISE EXCEPTION 'editor_conflict_copy_backend_only' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO v_source FROM edoc.official_documents
    WHERE id = p_bundle->>'source_document_id' FOR UPDATE;
  IF NOT FOUND OR v_source.applicant_id IS DISTINCT FROM v_actor THEN
    RAISE EXCEPTION 'official_editor_write_forbidden' USING ERRCODE = '42501';
  END IF;
  IF v_source.current_status NOT IN ('draft', 'rejected') THEN
    RAISE EXCEPTION 'editor_locked_after_submit' USING ERRCODE = 'PT409';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM edoc.users WHERE id = v_actor AND company_id = v_source.company_id AND status = '啟用') THEN
    RAISE EXCEPTION 'official_editor_company_forbidden' USING ERRCODE = '42501';
  END IF;
  SELECT * INTO v_existing FROM edoc.official_documents WHERE id = v_id;
  IF FOUND THEN
    v_meta := v_existing.metadata_json::jsonb->'conflict_recovery';
    IF v_existing.applicant_id IS DISTINCT FROM v_actor
      OR v_meta->>'source_document_id' IS DISTINCT FROM v_source.id
      OR v_meta->>'request_hash' IS DISTINCT FROM p_bundle->>'request_hash' THEN
      RAISE EXCEPTION 'editor_conflict_copy_request_conflict' USING ERRCODE = 'PT409';
    END IF;
    RETURN jsonb_build_object('document_id', v_id, 'idempotent', true);
  END IF;
  v_document := jsonb_populate_record(NULL::edoc.official_documents, p_bundle->'document');
  IF v_document.applicant_id IS DISTINCT FROM v_actor OR v_document.company_id IS DISTINCT FROM v_source.company_id
    OR v_document.current_status <> 'draft' OR v_document.source_type <> 'uploaded_pdf'
    OR coalesce((v_source.metadata_json::jsonb->>'pdf_editor_v2')::boolean, false) IS NOT TRUE THEN
    RAISE EXCEPTION 'editor_conflict_copy_invalid_document' USING ERRCODE = '42501';
  END IF;
  INSERT INTO edoc.official_documents SELECT v_document.*;
  IF p_bundle->'revision'->>'document_id' IS DISTINCT FROM v_id OR (p_bundle->'revision'->>'revision_no')::int <> 1 THEN
    RAISE EXCEPTION 'editor_conflict_copy_invalid_revision';
  END IF;
  INSERT INTO edoc.official_document_editor_revisions
    SELECT * FROM jsonb_populate_record(NULL::edoc.official_document_editor_revisions, p_bundle->'revision');
  FOR v_row IN SELECT value FROM jsonb_array_elements(p_bundle->'file_objects') LOOP
    IF v_row->>'document_id' IS DISTINCT FROM v_id THEN RAISE EXCEPTION 'editor_conflict_copy_invalid_asset'; END IF;
    INSERT INTO edoc.file_objects SELECT * FROM jsonb_populate_record(NULL::edoc.file_objects, v_row);
  END LOOP;
  FOR v_row IN SELECT value FROM jsonb_array_elements(p_bundle->'files') LOOP
    IF v_row->>'document_id' IS DISTINCT FROM v_id OR v_row->>'file_type' NOT IN ('original_pdf', 'attachment') THEN RAISE EXCEPTION 'editor_conflict_copy_invalid_asset'; END IF;
    INSERT INTO edoc.official_document_files SELECT * FROM jsonb_populate_record(NULL::edoc.official_document_files, v_row);
  END LOOP;
  FOR v_row IN SELECT value FROM jsonb_array_elements(p_bundle->'assets') LOOP
    IF v_row->>'document_id' IS DISTINCT FROM v_id OR v_row->>'asset_kind' NOT IN ('source_pdf', 'import_pdf', 'image')
      OR v_row->>'upload_status' <> 'finalized' OR v_row->>'scan_status' <> 'passed' OR v_row->>'preflight_status' <> 'passed' THEN
      RAISE EXCEPTION 'editor_conflict_copy_invalid_asset';
    END IF;
    -- Follow the same pending -> promoting -> finalized invariant as direct
    -- uploads. No trigger is disabled and no finalized source is overwritten.
    INSERT INTO edoc.official_document_editor_assets SELECT * FROM jsonb_populate_record(NULL::edoc.official_document_editor_assets,
      v_row || jsonb_build_object('upload_status', 'uploaded', 'storage_path', 'editor-copy-staging/' || v_id || '/' || (v_row->>'id')));
    INSERT INTO edoc.official_document_editor_storage_jobs
      (id, asset_id, document_id, staging_bucket, staging_path, final_bucket, final_path, expected_sha256, expected_size_bytes,
       token_expires_at, status, lease_token, lease_expires_at, final_file_object_id, attempt_count, last_error_code, created_at, updated_at)
    VALUES ('ODJOB-' || (v_row->>'id'), v_row->>'id', v_id, v_row->>'storage_bucket', 'editor-copy-staging/' || v_id || '/' || (v_row->>'id'),
      v_row->>'storage_bucket', v_row->>'storage_path', v_row->>'sha256', (v_row->>'size_bytes')::bigint,
      to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), 'pending', '', '',
      NULL, 0, '', to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), to_char(now(), 'YYYY-MM-DD HH24:MI:SS'));
    UPDATE edoc.official_document_editor_storage_jobs SET status='promoting', lease_token='copy-' || v_id,
      lease_expires_at=to_char(now() + interval '10 minutes', 'YYYY-MM-DD HH24:MI:SS'), attempt_count=1
      WHERE asset_id=v_row->>'id';
    UPDATE edoc.official_document_editor_assets SET upload_status = 'finalized' WHERE id = v_row->>'id';
  END LOOP;
  INSERT INTO edoc.official_document_approval_logs(id, document_id, actor_id, actor_name, action, comment, decision_evidence_json, created_at)
    VALUES ('ODLOG-' || v_id, v_id, v_actor, v_actor, 'editor_conflict_copy',
      'source_document_id=' || v_source.id || ';manifest=' || (p_bundle->'revision'->>'manifest_sha256'), '{}', now());
  RETURN jsonb_build_object('document_id', v_id, 'idempotent', false);
END;
$$;
REVOKE ALL ON FUNCTION edoc.edoc_copy_editor_conflict(jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION edoc.edoc_copy_editor_conflict(jsonb) TO edoc_backend;
$source_1$;
    insert into edoc_private.shared_project_migration_ledger(file_name,source_sha256,transformed_sha256,bundle_version)
      values('20260911133603_editor_conflict_copy_atomic.sql','f5485567cb3ab348cc8f44b408d06d5ab5aa0f56e66d0daf6b840a27e16618b8','909efc2dee65fc2b897f741e3e86f25d580359ee6c8f6cf1eef55346b14daac2','shared-project-schema-v1');
  end if;
end $forward_1$;

-- The dedicated backend has no BYPASSRLS; permit rows only to that backend.
drop policy if exists edoc_backend_compose_drafts on edoc.official_document_compose_drafts;
create policy edoc_backend_compose_drafts on edoc.official_document_compose_drafts
  to edoc_backend using(true) with check(true);
revoke all on edoc.official_document_compose_drafts from public,anon,authenticated,service_role,authenticator;
revoke all on function edoc.edoc_save_compose_draft(text,text,text,integer,jsonb,text,boolean),
  edoc.edoc_copy_editor_conflict(jsonb) from public,anon,authenticated,service_role,authenticator;
notify pgrst, 'reload schema';
commit;
