-- Generated by tools/editor_applicant_shared_forward.py; source hashes are locked.
-- Only two V2 application/workflow forwards in the private edoc namespace.
-- No source assets, Finance organization rows, user identities or grants change.
begin;
select pg_catalog.pg_advisory_xact_lock(1788103601, 20260913);
do $preflight$
begin
  if pg_catalog.to_regclass('edoc_private.shared_project_migration_ledger') is null
     or pg_catalog.to_regclass('edoc.official_documents') is null
     or not exists(select 1 from pg_catalog.pg_roles where rolname='edoc_backend' and not rolbypassrls)
     or not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260911133144_compose_resilience_drafts_revision.sql')
     or not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260911133603_editor_conflict_copy_atomic.sql') then
    raise exception 'shared_editor_applicant_preflight_failed';
  end if;
end $preflight$;

do $forward_0$
begin
  if exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260913055452_editor_applicant_selection_scope.sql'
    and (source_sha256 <> 'f9c6d7b68dd4d5f02fa2adce41f575d4b5ff59126805b5f0d1ff5f6f0d6972a3' or transformed_sha256 <> '50e88a69464500ea53da4c744a4265a41f3dacdbc74accca7290c2cafc046532')) then
    raise exception 'shared_editor_applicant_source_hash_mismatch';
  end if;
  if not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260913055452_editor_applicant_selection_scope.sql') then
    execute $source_0$
-- Creation-only V2 application scope. The real actor/Finance role stays intact;
-- no company-record access, browser grants, company mutation or file reparenting.
do $migration$
declare
  v_proc regprocedure;
  v_sql text;
  v_old text;
  v_new text;
begin
  v_proc := 'edoc.edoc_apply_official_document_correction(text,text,text,jsonb,text,jsonb,jsonb,text,jsonb,jsonb,text,text,text,text,text,text,jsonb,text,text)'::regprocedure;
  v_sql := pg_catalog.pg_get_functiondef(v_proc);
  v_old := '''dispatch_unit'', ''handler_name'', ''request_reason'',';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'editor_applicant_patch_keys_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, v_old || ' ''applicant_department_id'', ''applicant_department_name'',');
  v_old := '         dispatch_unit = case when p_patch ? ''dispatch_unit'' then p_patch->>''dispatch_unit'' else dispatch_unit end,';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'editor_applicant_patch_write_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, v_old || $snippet$
         applicant_department_id = case when p_patch ? 'applicant_department_id' then p_patch->>'applicant_department_id' else applicant_department_id end,
         applicant_department_name = case when p_patch ? 'applicant_department_name' then p_patch->>'applicant_department_name' else applicant_department_name end,
$snippet$);
  v_old := '  select actor.*';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'editor_applicant_patch_validation_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, $snippet$
  if p_patch ? 'applicant_department_id' or p_patch ? 'applicant_department_name' then
    if v_document.source_type <> 'uploaded_pdf'
       or coalesce(v_document.metadata_json::jsonb->>'pdf_editor_v2', 'false') <> 'true'
       or nullif(btrim(p_patch->>'applicant_department_id'), '') is null
       or nullif(btrim(p_patch->>'applicant_department_name'), '') is null
       or p_patch->>'dispatch_unit' is distinct from p_patch->>'applicant_department_name' then
      raise exception using errcode = '42501', message = 'finance_unit_payload_mismatch';
    end if;
    if (select count(*) from edoc.finance_organization_units as unit
          join edoc.companies as company on company.id = v_document.company_id
         where unit.finance_tenant_id = company.finance_tenant_id
           and upper(unit.code) = upper(p_patch->>'applicant_department_id')
           and unit.status = 'active') <> 1
       or not exists (select 1 from edoc.finance_organization_units as unit
          join edoc.companies as company on company.id = v_document.company_id
         where unit.finance_tenant_id = company.finance_tenant_id
           and upper(unit.code) = upper(p_patch->>'applicant_department_id')
           and unit.name = p_patch->>'applicant_department_name' and unit.status = 'active') then
      raise exception using errcode = '42501', message = 'finance_unit_projection_unavailable';
    end if;
  end if;
  select actor.*
$snippet$);
  execute v_sql;

  -- Both functions already lock the document and require its actual applicant.
  -- Retain the old path for every non-V2 case and add only same-tenant V2 scope.
  for v_proc in select unnest(array[
    'edoc.edoc_apply_official_document_correction(text,text,text,jsonb,text,jsonb,jsonb,text,jsonb,jsonb,text,text,text,text,text,text,jsonb,text,text)'::regprocedure,
    'edoc.edoc_finalize_official_document_resubmit(text,text,text,timestamp with time zone,text,text,text,text,text)'::regprocedure
  ]) loop
    v_sql := pg_catalog.pg_get_functiondef(v_proc);
    v_old := '     and actor.company_id = p_company_id';
    if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'editor_applicant_actor_scope_drift'; end if;
    v_new := $snippet$
     and (actor.company_id = p_company_id or (
       v_document.source_type = 'uploaded_pdf'
       and coalesce(v_document.metadata_json::jsonb->>'pdf_editor_v2', 'false') = 'true'
       and nullif(btrim(actor.finance_tenant_id::text), '') is not null
       and exists (select 1 from edoc.companies as company
         where company.id = p_company_id and company.finance_tenant_id = actor.finance_tenant_id
           and company.source_system = 'finance' and company.status in ('active', '啟用')
           and nullif(btrim(company.finance_entity_id), '') is not null)
     ))
$snippet$;
    execute pg_catalog.replace(v_sql, v_old, v_new);
  end loop;

  v_proc := 'edoc.edoc_copy_editor_conflict(jsonb)'::regprocedure;
  v_sql := pg_catalog.pg_get_functiondef(v_proc);
  v_old := 'SELECT 1 FROM edoc.users WHERE id = v_actor AND company_id = v_source.company_id AND status = ''啟用''';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'editor_applicant_copy_scope_drift'; end if;
  v_new := $snippet$SELECT 1 FROM edoc.users as actor WHERE actor.id = v_actor AND actor.status = '啟用'
    AND (actor.company_id = v_source.company_id OR (
      v_source.source_type = 'uploaded_pdf'
      AND coalesce(v_source.metadata_json::jsonb->>'pdf_editor_v2', 'false') = 'true'
      AND nullif(btrim(actor.finance_tenant_id::text), '') IS NOT NULL
      AND EXISTS (SELECT 1 FROM edoc.companies as company WHERE company.id = v_source.company_id
        AND company.finance_tenant_id = actor.finance_tenant_id AND company.source_system = 'finance'
        AND company.status IN ('active', '啟用') AND nullif(btrim(company.finance_entity_id), '') IS NOT NULL)
    ))$snippet$;
  execute pg_catalog.replace(v_sql, v_old, v_new);
end $migration$;
$source_0$;
    insert into edoc_private.shared_project_migration_ledger(file_name,source_sha256,transformed_sha256,bundle_version)
      values('20260913055452_editor_applicant_selection_scope.sql','f9c6d7b68dd4d5f02fa2adce41f575d4b5ff59126805b5f0d1ff5f6f0d6972a3','50e88a69464500ea53da4c744a4265a41f3dacdbc74accca7290c2cafc046532','shared-project-schema-v1');
  end if;
end $forward_0$;

do $forward_1$
begin
  if exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260913060040_editor_cross_company_workflow_scope.sql'
    and (source_sha256 <> 'b1e3bc0e5aef722218a724fef3a6ae7ad5cf7d8ff63e0b5255fe2e832f1743db' or transformed_sha256 <> 'b584a46d192a3b5dc582bddd5d2a35fe310e801670df1e7b383e338de3f7b56d')) then
    raise exception 'shared_editor_applicant_source_hash_mismatch';
  end if;
  if not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260913060040_editor_cross_company_workflow_scope.sql') then
    execute $source_1$
-- V2 selected-company cases keep their real Finance applicant/approvers.
-- These private predicates add only a same-verified-tenant exception to the
-- existing exact actor/step/owner checks. Generic company access is unchanged.
create or replace function edoc_private.editor_v2_actor_in_company_scope(p_document_id text, p_actor_id text)
returns boolean language sql stable security invoker set search_path = '' as $function$
  select exists (
    select 1 from edoc.official_documents as document
    join edoc.companies as company on company.id = document.company_id
    join edoc.users as applicant on applicant.id = document.applicant_id
    join edoc.users as actor on actor.id = p_actor_id
    where document.id = p_document_id and document.source_type = 'uploaded_pdf'
      and coalesce(document.metadata_json::jsonb->>'pdf_editor_v2', 'false') = 'true'
      and company.source_system = 'finance' and company.status in ('active', '啟用')
      and nullif(btrim(company.finance_entity_id), '') is not null
      and nullif(btrim(company.finance_tenant_id::text), '') is not null
      and applicant.finance_tenant_id = company.finance_tenant_id and applicant.status = '啟用'
      and actor.finance_tenant_id = company.finance_tenant_id and actor.status = '啟用'
  )
$function$;

create or replace function edoc_private.editor_v2_case_participant(p_document_id text, p_actor_id text)
returns boolean language sql stable security invoker set search_path = '' as $function$
  select edoc_private.editor_v2_actor_in_company_scope(p_document_id, p_actor_id) and (
    exists (select 1 from edoc.official_documents where id = p_document_id and applicant_id = p_actor_id)
    or exists (select 1 from edoc.official_document_approval_steps
      where document_id = p_document_id and (approver_user_id = p_actor_id or decision_actor_user_id = p_actor_id))
    or exists (select 1 from edoc.approval_step_actor_snapshots
      where source_type in ('official_document','official_documents','official_document_application')
        and source_id = p_document_id and approver_user_id = p_actor_id)
  )
$function$;

create or replace function edoc_private.assert_official_document_decision_actor(
  p_document_id text, p_company_id text, p_principal_user_id text, p_decision_actor_user_id text
) returns void language plpgsql security invoker set search_path = '' as $function$
declare v_now timestamptz := pg_catalog.clock_timestamp();
begin
  if not exists (select 1 from edoc.official_documents where id = p_document_id and company_id = p_company_id) then
    raise exception using errcode = '42501', message = 'official_document_company_forbidden';
  end if;
  if not edoc_private.editor_v2_actor_in_company_scope(p_document_id, p_principal_user_id)
     or not edoc_private.editor_v2_actor_in_company_scope(p_document_id, p_decision_actor_user_id) then
    -- Retain precisely the old boundary for non-V2 or non-qualified actors.
    perform edoc_private.assert_official_decision_actor(p_company_id, p_principal_user_id, p_decision_actor_user_id);
    return;
  end if;
  if not exists (select 1 from edoc.official_document_approval_steps
      where document_id = p_document_id and approver_user_id = p_principal_user_id) then
    raise exception using errcode = '42501', message = 'not_current_official_document_approver';
  end if;
  if p_decision_actor_user_id <> p_principal_user_id and not exists (
    select 1 from edoc.official_workflow_delegations as delegation
    where delegation.company_id = p_company_id and delegation.principal_user_id = p_principal_user_id
      and delegation.delegate_user_id = p_decision_actor_user_id and delegation.status = 'active'
      and delegation.starts_at <= v_now and delegation.ends_at > v_now
  ) then
    raise exception using errcode = '42501', message = 'official_workflow_delegation_not_active';
  end if;
end
$function$;

revoke all on function edoc_private.editor_v2_actor_in_company_scope(text,text) from public,anon,authenticated,edoc_backend;
revoke all on function edoc_private.editor_v2_case_participant(text,text) from public,anon,authenticated,edoc_backend;
revoke all on function edoc_private.assert_official_document_decision_actor(text,text,text,text) from public,anon,authenticated,edoc_backend;

do $migration$
declare v_proc regprocedure; v_sql text; v_old text; v_new text;
begin
  -- The callers still prove the exact requested step/principal, self-approval
  -- prohibition, immutable review hashes and lock order. Pass document context
  -- to a new wrapper; never broaden the old three-argument helper globally.
  for v_proc in select unnest(array[
    'edoc.edoc_claim_official_document_approval_v2(text,text,text,text,text,jsonb)'::regprocedure,
    'edoc.edoc_claim_official_document_rejection_v2(text,text,text,text,text,jsonb)'::regprocedure,
    'edoc_private.validate_official_document_decision_evidence(text,text,text,text,text,jsonb)'::regprocedure
  ]) loop
    v_sql := pg_catalog.pg_get_functiondef(v_proc);
    v_old := E'perform edoc_private.assert_official_decision_actor(\n    v_document.company_id,';
    v_new := E'perform edoc_private.assert_official_document_decision_actor(\n    v_document.id, v_document.company_id,';
    if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'editor_decision_scope_call_drift'; end if;
    execute pg_catalog.replace(v_sql, v_old, v_new);
  end loop;

  v_proc := 'edoc.edoc_claim_official_document_approval_v2(text,text,text,text,text,jsonb)'::regprocedure;
  v_sql := pg_catalog.pg_get_functiondef(v_proc);
  v_old := 'and next_actor.company_id = v_document.company_id';
  v_new := 'and (next_actor.company_id = v_document.company_id or edoc_private.editor_v2_actor_in_company_scope(v_document.id,next_actor.id))';
  if pg_catalog.strpos(v_sql,v_old)=0 then raise exception 'editor_next_actor_scope_drift'; end if;
  v_sql := pg_catalog.replace(v_sql,v_old,v_new);
  v_old := E'v_document.company_id,\n        (select u.email';
  v_new := E'(select u.company_id from edoc.users as u where u.id = v_result#>>''{next_step,approver_user_id}''),\n        (select u.email';
  if pg_catalog.strpos(v_sql,v_old)=0 then raise exception 'editor_next_notification_scope_drift'; end if;
  execute pg_catalog.replace(v_sql,v_old,v_new);

  v_proc := 'edoc.edoc_claim_official_document_rejection_v2(text,text,text,text,text,jsonb)'::regprocedure;
  v_sql := pg_catalog.pg_get_functiondef(v_proc);
  v_old := 'and applicant.company_id = v_document.company_id';
  v_new := 'and (applicant.company_id = v_document.company_id or edoc_private.editor_v2_actor_in_company_scope(v_document.id,applicant.id))';
  if pg_catalog.strpos(v_sql,v_old)=0 then raise exception 'editor_return_actor_scope_drift'; end if;
  v_sql := pg_catalog.replace(v_sql,v_old,v_new);
  v_old := E'v_document.company_id,\n      (select u.email';
  v_new := E'(select u.company_id from edoc.users as u where u.id = v_document.applicant_id),\n      (select u.email';
  if pg_catalog.strpos(v_sql,v_old)=0 then raise exception 'editor_return_notification_scope_drift'; end if;
  execute pg_catalog.replace(v_sql,v_old,v_new);

  v_proc := 'edoc.edoc_create_official_document_dispatch_record(text,text)'::regprocedure;
  v_sql := pg_catalog.pg_get_functiondef(v_proc);
  v_old := 'and actor.company_id = v_document.company_id';
  v_new := 'and (actor.company_id = v_document.company_id or edoc_private.editor_v2_case_participant(v_document.id,actor.id))';
  if pg_catalog.strpos(v_sql,v_old)=0 then raise exception 'editor_dispatch_actor_scope_drift'; end if;
  execute pg_catalog.replace(v_sql,v_old,v_new);

  v_proc := 'edoc.edoc_complete_official_document_dispatch(text,text,text,text,text,text,text,text,text,text)'::regprocedure;
  v_sql := pg_catalog.pg_get_functiondef(v_proc);
  v_old := 'and app_user.company_id = v_document.company_id';
  v_new := 'and (app_user.company_id = v_document.company_id or edoc_private.editor_v2_case_participant(v_document.id,app_user.id))';
  if (pg_catalog.length(v_sql)-pg_catalog.length(pg_catalog.replace(v_sql,v_old,''))) / pg_catalog.length(v_old) <> 2 then
    raise exception 'editor_dispatch_complete_scope_drift';
  end if;
  execute pg_catalog.replace(v_sql,v_old,v_new);

  v_proc := 'edoc.edoc_register_official_archive_export(text,text,text,text,text,integer,bigint,text,text,text)'::regprocedure;
  v_sql := pg_catalog.pg_get_functiondef(v_proc);
  v_old := 'if v_user.company_id is distinct from v_document.company_id then';
  v_new := 'if v_user.company_id is distinct from v_document.company_id and not edoc_private.editor_v2_case_participant(v_document.id,v_user.id) then';
  if pg_catalog.strpos(v_sql,v_old)=0 then raise exception 'editor_archive_actor_scope_drift'; end if;
  execute pg_catalog.replace(v_sql,v_old,v_new);
end
$migration$;
$source_1$;
    insert into edoc_private.shared_project_migration_ledger(file_name,source_sha256,transformed_sha256,bundle_version)
      values('20260913060040_editor_cross_company_workflow_scope.sql','b1e3bc0e5aef722218a724fef3a6ae7ad5cf7d8ff63e0b5255fe2e832f1743db','b584a46d192a3b5dc582bddd5d2a35fe310e801670df1e7b383e338de3f7b56d','shared-project-schema-v1');
  end if;
end $forward_1$;

notify pgrst, 'reload schema';
commit;
