-- Generated by tools/compose_shared_forward.py from the frozen source deltas.
-- One transaction; no public HR tables, real exchange provider, or file bytes.
begin;
select pg_catalog.pg_advisory_xact_lock(1788103601, 20260908);
do $shared_compose_preflight$
begin
  if pg_catalog.to_regclass('edoc_private.shared_project_migration_ledger') is null
     or pg_catalog.to_regclass('edoc.official_documents') is null
     or not exists (select 1 from pg_catalog.pg_roles where rolname='edoc_backend' and not rolbypassrls)
     or not exists (select 1 from edoc_private.shared_project_migration_ledger
       where file_name='20260827050450_atomic_official_submission_editor_finalize_forward.sql')
     or not exists (select 1 from edoc_private.shared_project_migration_ledger
       where file_name='20260827133545_fix_official_document_function_type_resolution.sql') then
    raise exception 'shared_compose_preflight_failed';
  end if;
end;
$shared_compose_preflight$;

do $shared_compose_forward_0$
begin
  if exists (select 1 from edoc_private.shared_project_migration_ledger
    where file_name='20260908135730_immutable_official_document_numbering.sql' and
      (source_sha256 <> '93c4b7c1493a5260417000ab9f4e7074b41b6f8cb2c0e30f212d5006dbb1c0d9' or transformed_sha256 <> 'df28f1b2c89974928178fd129e89e8b1e1dd2090cc991642e5f470e079c52ce4')) then
    raise exception 'shared_compose_source_hash_mismatch';
  end if;
  if not exists (select 1 from edoc_private.shared_project_migration_ledger where file_name='20260908135730_immutable_official_document_numbering.sql') then
    execute $shared_compose_source_0$
-- Persist numbers at first draft save. Never renumber historical cases.
ALTER TABLE edoc.official_documents ADD COLUMN IF NOT EXISTS dispatch_no text;
CREATE UNIQUE INDEX IF NOT EXISTS ux_official_documents_dispatch_no
  ON edoc.official_documents(dispatch_no) WHERE dispatch_no IS NOT NULL;

CREATE TABLE IF NOT EXISTS edoc.official_document_number_counters (
  date_key text PRIMARY KEY,
  last_serial bigint NOT NULL CHECK (last_serial > 0)
);
CREATE TABLE IF NOT EXISTS edoc.official_document_number_allocations (
  document_id text PRIMARY KEY REFERENCES edoc.official_documents(id) ON DELETE RESTRICT,
  company_id text NOT NULL REFERENCES edoc.companies(id) ON DELETE RESTRICT,
  applicant_id text NOT NULL,
  dispatch_no text NOT NULL UNIQUE,
  assigned_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE edoc.official_document_number_counters ENABLE ROW LEVEL SECURITY;
ALTER TABLE edoc.official_document_number_allocations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON edoc.official_document_number_counters FROM PUBLIC, anon, authenticated;
REVOKE ALL ON edoc.official_document_number_allocations FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON edoc.official_document_number_counters TO edoc_backend;
GRANT SELECT, INSERT ON edoc.official_document_number_allocations TO edoc_backend;

CREATE OR REPLACE FUNCTION edoc.edoc_number_safe_metadata(p_value text)
RETURNS jsonb LANGUAGE plpgsql IMMUTABLE SECURITY INVOKER SET search_path = '' AS $$
BEGIN
  RETURN COALESCE(p_value::jsonb, '{}'::jsonb);
EXCEPTION WHEN invalid_text_representation THEN RETURN '{}'::jsonb;
END;
$$;

CREATE OR REPLACE FUNCTION edoc.edoc_allocate_official_number()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
DECLARE
  v_today date := (statement_timestamp() AT TIME ZONE 'Asia/Taipei')::date;
  v_key text;
  v_prefix text;
  v_floor bigint;
  v_serial bigint;
BEGIN
  IF NEW.dispatch_no IS NOT NULL THEN
    RAISE EXCEPTION 'official_document_number_server_owned' USING ERRCODE = '23514';
  END IF;
  IF NEW.source_type <> 'blank_editor' THEN RETURN NEW; END IF;
  v_key := (extract(year FROM v_today)::integer - 1911)::text || to_char(v_today, 'MMDD');
  v_prefix := '歲悅字第' || v_key;
  -- A transaction-scoped lock includes the legacy floor lookup and upsert.
  -- Same-prefix callers serialize; unrelated transactions remain unblocked.
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('edoc.number.' || v_key, 0));
  SELECT COALESCE(max(serial::bigint), 0) INTO v_floor FROM (
    SELECT substring(value FROM char_length(v_prefix) + 1 FOR char_length(value) - char_length(v_prefix) - 1) AS serial
    FROM (
      SELECT d.doc_no AS value FROM edoc.documents d WHERE d.direction = '發文'
      UNION ALL SELECT d.dispatch_no FROM edoc.official_documents d
      UNION ALL SELECT edoc.edoc_number_safe_metadata(d.metadata_json)->>'dispatch_no' FROM edoc.official_documents d
      UNION ALL SELECT edoc.edoc_number_safe_metadata(d.metadata_json)#>>'{extra,dispatch_no}' FROM edoc.official_documents d
    ) existing
    WHERE value LIKE v_prefix || '%號'
  ) parts WHERE serial ~ '^[0-9]{1,12}$';
  INSERT INTO edoc.official_document_number_counters AS counters(date_key, last_serial)
  VALUES (v_key, v_floor + 1)
  ON CONFLICT (date_key) DO UPDATE
    SET last_serial = greatest(counters.last_serial, v_floor) + 1
  RETURNING last_serial INTO v_serial;
  NEW.dispatch_no := v_prefix || lpad(v_serial::text, greatest(3, char_length(v_serial::text)), '0') || '號';
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION edoc.edoc_record_official_number()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
BEGIN
  IF NEW.dispatch_no IS NOT NULL THEN
    INSERT INTO edoc.official_document_number_allocations(document_id, company_id, applicant_id, dispatch_no)
    VALUES (NEW.id, NEW.company_id, NEW.applicant_id, NEW.dispatch_no);
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION edoc.edoc_guard_official_number()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
BEGIN
  IF NEW.dispatch_no IS DISTINCT FROM OLD.dispatch_no OR
    (OLD.dispatch_no IS NOT NULL AND (
      NEW.company_id IS DISTINCT FROM OLD.company_id OR
      NEW.applicant_id IS DISTINCT FROM OLD.applicant_id OR
      NEW.source_type IS DISTINCT FROM OLD.source_type
    )) THEN
    RAISE EXCEPTION 'official_document_number_immutable' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION edoc.edoc_guard_number_allocation()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
BEGIN
  RAISE EXCEPTION 'official_document_number_immutable' USING ERRCODE = '23514';
END;
$$;

DROP TRIGGER IF EXISTS trg_official_number_allocate ON edoc.official_documents;
CREATE TRIGGER trg_official_number_allocate BEFORE INSERT ON edoc.official_documents
  FOR EACH ROW EXECUTE FUNCTION edoc.edoc_allocate_official_number();
DROP TRIGGER IF EXISTS trg_official_number_record ON edoc.official_documents;
CREATE TRIGGER trg_official_number_record AFTER INSERT ON edoc.official_documents
  FOR EACH ROW EXECUTE FUNCTION edoc.edoc_record_official_number();
DROP TRIGGER IF EXISTS trg_official_number_immutable ON edoc.official_documents;
CREATE TRIGGER trg_official_number_immutable BEFORE UPDATE OF dispatch_no, company_id, applicant_id, source_type
  ON edoc.official_documents FOR EACH ROW EXECUTE FUNCTION edoc.edoc_guard_official_number();
CREATE TRIGGER trg_official_number_allocation_immutable BEFORE UPDATE OR DELETE
  ON edoc.official_document_number_allocations FOR EACH ROW EXECUTE FUNCTION edoc.edoc_guard_number_allocation();

REVOKE ALL ON FUNCTION edoc.edoc_number_safe_metadata(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION edoc.edoc_allocate_official_number() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION edoc.edoc_record_official_number() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION edoc.edoc_guard_official_number() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION edoc.edoc_guard_number_allocation() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION edoc.edoc_number_safe_metadata(text) TO edoc_backend;
GRANT EXECUTE ON FUNCTION edoc.edoc_allocate_official_number() TO edoc_backend;
GRANT EXECUTE ON FUNCTION edoc.edoc_record_official_number() TO edoc_backend;
GRANT EXECUTE ON FUNCTION edoc.edoc_guard_official_number() TO edoc_backend;
GRANT EXECUTE ON FUNCTION edoc.edoc_guard_number_allocation() TO edoc_backend;
$shared_compose_source_0$;
    insert into edoc_private.shared_project_migration_ledger
      (file_name,source_sha256,transformed_sha256,bundle_version)
    values ('20260908135730_immutable_official_document_numbering.sql','93c4b7c1493a5260417000ab9f4e7074b41b6f8cb2c0e30f212d5006dbb1c0d9','df28f1b2c89974928178fd129e89e8b1e1dd2090cc991642e5f470e079c52ce4','shared-project-schema-v1');
  end if;
end;
$shared_compose_forward_0$;

do $shared_compose_forward_1$
begin
  if exists (select 1 from edoc_private.shared_project_migration_ledger
    where file_name='20260908135911_compose_electronic_output_dispatch_date.sql' and
      (source_sha256 <> '88263ed13770f367d245b91a05661f1b4a455715fd9aa71fc1429d87e1d4822e' or transformed_sha256 <> '51f059492eb924cecaff0f427fe77d206ef8793c7ac6839605f61413ab5d00d3')) then
    raise exception 'shared_compose_source_hash_mismatch';
  end if;
  if not exists (select 1 from edoc_private.shared_project_migration_ledger where file_name='20260908135911_compose_electronic_output_dispatch_date.sql') then
    execute $shared_compose_source_1$
-- Explicit compose output mode; an uploaded PDF must still use Seal Vault.
alter table edoc.official_documents
  add column if not exists output_mode text not null default 'physical',
  add column if not exists dispatch_date text;
grant usage on schema edoc_private to edoc_backend;

create or replace function edoc_private.is_electronic_compose(p_document edoc.official_documents)
returns boolean language sql immutable security invoker set search_path = ''
as $$
  select coalesce(p_document.output_mode = 'electronic'
    and p_document.source_type = 'blank_editor'
    and p_document.document_type = 'outgoing_official_document'
    and p_document.requires_stamp is false, false)
$$;
revoke all on function edoc_private.is_electronic_compose(edoc.official_documents) from public, anon, authenticated;
grant execute on function edoc_private.is_electronic_compose(edoc.official_documents) to edoc_backend;

create or replace function edoc_private.guard_compose_output_fields()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if new.output_mode not in ('physical', 'electronic')
     or (new.output_mode = 'electronic' and not edoc_private.is_electronic_compose(new))
     or (new.output_mode = 'physical' and new.requires_stamp is not true) then
    raise exception using errcode = '42501', message = 'official_document_output_mode_invalid';
  end if;
  if new.dispatch_date is not null and (
    new.dispatch_date !~ '^\d{4}-\d{2}-\d{2}$'
    or pg_catalog.to_char(new.dispatch_date::date, 'YYYY-MM-DD') <> new.dispatch_date
  ) then
    raise exception using errcode = '22023', message = 'official_dispatch_date_invalid';
  end if;
  if tg_op = 'UPDATE' then
    if old.current_status <> 'draft' and (
      old.output_mode is distinct from new.output_mode
      or old.requires_stamp is distinct from new.requires_stamp
    ) then
      raise exception using errcode = '55000', message = 'official_document_output_mode_locked';
    end if;
    if old.current_status not in ('draft', 'rejected') and old.dispatch_date is distinct from new.dispatch_date then
      raise exception using errcode = '55000', message = 'official_document_dispatch_date_locked';
    end if;
  end if;
  return new;
end;
$$;
revoke all on function edoc_private.guard_compose_output_fields() from public, anon, authenticated;
drop trigger if exists trg_guard_compose_output_fields on edoc.official_documents;
create trigger trg_guard_compose_output_fields before insert or update of output_mode, requires_stamp, dispatch_date
on edoc.official_documents for each row execute function edoc_private.guard_compose_output_fields();

-- Preserve the established atomic RPCs and their authorization/audit logic.
-- These exact, checked replacements fail the migration if the expected prior
-- definitions have drifted instead of silently installing a partial workflow.
do $migration$
declare
  v_sql text;
  v_old text;
  v_new text;
  v_proc regprocedure;
begin
  v_proc := 'edoc.edoc_commit_official_document_submission(jsonb)'::regprocedure;
  v_sql := pg_catalog.pg_get_functiondef(v_proc);
  v_old := '  v_position_count integer;';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_submit_declaration_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, v_old || E'\n  v_electronic boolean := false;');
  v_old := '  v_stamp := pg_catalog.jsonb_populate_record(null::edoc.official_document_stamp_requests, p_request->''stamp_request'');';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_submit_source_drift'; end if;
  v_new := $snippet$
  v_electronic := edoc_private.is_electronic_compose(v_document);
  if not v_document.requires_stamp and not v_electronic then
    raise exception using errcode = '42501', message = 'official_document_stamp_required';
  end if;
  if v_electronic and not exists (
    select 1 from edoc.official_document_files f join edoc.file_objects o on o.id = f.file_object_id
    where f.document_id = v_document.id and f.file_type = 'generated_pdf'
      and f.id = p_request#>>'{submit_log,decision_evidence_json,source_file_id}'
      and f.file_hash = p_request#>>'{submit_log,decision_evidence_json,source_sha256}'
      and o.document_id = v_document.id and o.sha256 = f.file_hash and o.mime_type = 'application/pdf'
  ) then
    raise exception using errcode = '22023', message = 'official_document_electronic_source_invalid';
  end if;
$snippet$;
  v_sql := pg_catalog.replace(v_sql, v_old, v_new || v_old);
  v_old := '  if v_stamp.id is null or v_stamp.document_id is distinct from v_document_id';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_submit_stamp_guard_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, '  if (not v_electronic and (v_stamp.id is null or v_stamp.document_id is distinct from v_document_id');
  v_old := '     or v_submit_log.id is distinct from v_operation_id';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_submit_log_guard_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, '     )) or v_submit_log.id is distinct from v_operation_id');
  v_old := '  if v_position_count < 1 or exists (';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_submit_position_guard_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, '  if (not v_electronic and v_position_count < 1) or (v_electronic and v_position_count <> 0) or exists (');
  v_old := '       and v_existing_log.decision_evidence_json->>''stamp_request_id'' = p_request#>>''{stamp_request,id}''';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_submit_retry_id_drift'; end if;
  v_sql := pg_catalog.replace(v_sql,
    v_old,
    '       and coalesce(v_existing_log.decision_evidence_json->>''stamp_request_id'', '''') = coalesce(p_request#>>''{stamp_request,id}'', '''')');
  v_old := E'       and exists (\n         select 1 from edoc.official_document_stamp_requests request';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_submit_retry_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, E'       and (edoc_private.is_electronic_compose(v_document) or exists (\n         select 1 from edoc.official_document_stamp_requests request');
  v_old := E'           and request.requested_by = v_applicant_id\n       )';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_submit_retry_owner_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, E'           and request.requested_by = v_applicant_id\n       ))');
  v_old := '  insert into edoc.official_document_stamp_requests';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_submit_write_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, E'  if not v_electronic then\n' || v_old);
  v_old := E'  for v_step in\n    select * from pg_catalog.jsonb_populate_recordset';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_submit_steps_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, E'  end if;\n' || v_old);
  execute v_sql;

  v_proc := 'edoc.edoc_claim_official_document_approval(text,text,text,text)'::regprocedure;
  v_sql := pg_catalog.pg_get_functiondef(v_proc);
  v_old := '  if v_document.requires_stamp is distinct from true then';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_approval_guard_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old,
    '  if v_document.requires_stamp is distinct from true and not edoc_private.is_electronic_compose(v_document) then');
  v_old := E'    v_transition := ''auto_stamp'';\n    v_next_status := ''approved'';\n    v_next_key := ''auto_stamp'';';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_approval_transition_drift'; end if;
  v_new := $snippet$
    v_transition := case when edoc_private.is_electronic_compose(v_document) then 'electronic_dispatch' else 'auto_stamp' end;
    v_next_status := 'approved';
    v_next_key := v_transition;
$snippet$;
  v_sql := pg_catalog.replace(v_sql, v_old, v_new);
  execute v_sql;

  v_proc := 'edoc.edoc_apply_official_document_correction(text,text,text,jsonb,text,jsonb,jsonb,text,jsonb,jsonb,text,text,text,text,text,text,jsonb,text,text)'::regprocedure;
  v_sql := pg_catalog.pg_get_functiondef(v_proc);
  v_old := '       ''workflow_template_key'', ''metadata_json''';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_correction_allowlist_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, '       ''workflow_template_key'', ''metadata_json'', ''dispatch_date'', ''output_mode'', ''requires_stamp''');
  v_old := '         workflow_template_key = p_patch->>''workflow_template_key'',';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_correction_write_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, $snippet$
         dispatch_date = case when p_patch ? 'dispatch_date' then p_patch->>'dispatch_date' else dispatch_date end,
         output_mode = case when p_patch ? 'output_mode' then p_patch->>'output_mode' else output_mode end,
         requires_stamp = case when p_patch ? 'requires_stamp' then (p_patch->>'requires_stamp')::boolean else requires_stamp end,
         workflow_template_key = p_patch->>'workflow_template_key',
$snippet$);
  execute v_sql;
end;
$migration$;

create or replace function edoc_private.complete_electronic_compose(p_document_id text, p_actor_user_id text)
returns void language plpgsql security definer set search_path = '' as $$
declare
  v_document edoc.official_documents%rowtype;
  v_file edoc.official_document_files%rowtype;
  v_record jsonb;
  v_generation integer;
  v_submit_evidence jsonb;
  v_timestamp text := pg_catalog.to_char(pg_catalog.clock_timestamp(), 'YYYY-MM-DD HH24:MI:SS');
begin
  select * into v_document from edoc.official_documents where id = p_document_id for update;
  if not found or not edoc_private.is_electronic_compose(v_document)
     or v_document.current_status <> 'approved' or v_document.current_step <> 'electronic_dispatch' then
    raise exception using errcode = '42501', message = 'official_document_electronic_output_forbidden';
  end if;
  select max(workflow_generation) into v_generation from edoc.official_document_approval_steps where document_id = p_document_id;
  if v_generation is null or exists (
    select 1 from edoc.official_document_approval_steps where document_id = p_document_id
      and workflow_generation = v_generation and step_key <> 'applicant_confirm' and status <> 'approved'
  ) then
    raise exception using errcode = '55000', message = 'official_document_not_fully_approved';
  end if;
  select decision_evidence_json into v_submit_evidence from edoc.official_document_approval_logs
    where document_id = p_document_id and action = 'submit'
      and (decision_evidence_json->>'workflow_generation')::integer = v_generation
    order by created_at desc limit 1;
  select f.* into v_file from edoc.official_document_files f join edoc.file_objects o on o.id = f.file_object_id
    where f.document_id = p_document_id and f.file_type = 'generated_pdf'
      and f.id = v_submit_evidence->>'source_file_id'
      and f.file_hash = v_submit_evidence->>'source_sha256'
      and o.document_id = p_document_id and o.sha256 = f.file_hash and o.mime_type = 'application/pdf';
  if not found then raise exception using errcode = '22023', message = 'official_document_electronic_source_invalid'; end if;
  v_record := edoc.edoc_create_official_document_dispatch_record(p_document_id, p_actor_user_id);
  update edoc.official_documents set stamped_file_id = v_file.id,
    current_status = 'pending_general_affairs_dispatch', current_step = 'general_affairs_dispatch', updated_at = v_timestamp
    where id = p_document_id;
  insert into edoc.official_document_approval_logs
    (id, document_id, file_id, actor_id, actor_name, action, comment, created_at)
    values ('ODLOG-ELECTRONIC-' || pg_catalog.md5(p_document_id || ':' || v_generation),
      p_document_id, v_file.id, p_actor_user_id, coalesce((select name from edoc.users where id = p_actor_user_id), p_actor_user_id),
      'electronic_output_approved', 'file_hash=' || v_file.file_hash, v_timestamp);
  insert into edoc.notifications
    (id, type, title, target_role, target_user_id, target_company_id, target_email, channel, status, priority, source, action_url, body, created_at)
    select 'NTF-ELECTRONIC-' || pg_catalog.md5(p_document_id || ':' || v_generation), '發文寄發待辦',
      v_document.title || ' 待總務寄發', coalesce(u.role, ''), u.id, v_document.company_id,
      coalesce(u.email, ''), 'Email + 系統通知', '未讀', '高', p_document_id,
      '/#officialDispatch?document=' || p_document_id, '電子公文已核准，請完成寄發並回填寄送日期與證明。', pg_catalog.clock_timestamp()
    from edoc.users u where u.id = v_record#>>'{record,dispatch_owner_user_id}'
      and u.status = '啟用' and nullif(pg_catalog.btrim(u.email), '') is not null;
  if not found then raise exception using errcode = '22023', message = 'notification_exact_target_required'; end if;
end;
$$;
revoke all on function edoc_private.complete_electronic_compose(text, text) from public, anon, authenticated, edoc_backend;

do $migration$
declare v_sql text; v_old text;
begin
  v_sql := pg_catalog.pg_get_functiondef('edoc.edoc_claim_official_document_approval_v3(text,text,text,text,text,jsonb)'::regprocedure);
  v_old := '  return v_result;';
  if pg_catalog.strpos(v_sql, v_old) = 0 then raise exception 'compose_migration_approval_finalize_drift'; end if;
  v_sql := pg_catalog.replace(v_sql, v_old, $snippet$
  if coalesce((v_result->>'claimed')::boolean, false) and v_result->>'transition' = 'electronic_dispatch' then
    perform edoc_private.complete_electronic_compose(p_document_id, p_decision_actor_user_id);
    v_result := v_result || pg_catalog.jsonb_build_object('document_status', 'pending_general_affairs_dispatch', 'document_step', 'general_affairs_dispatch');
  end if;
  return v_result;
$snippet$);
  execute v_sql;
end;
$migration$;
$shared_compose_source_1$;
    insert into edoc_private.shared_project_migration_ledger
      (file_name,source_sha256,transformed_sha256,bundle_version)
    values ('20260908135911_compose_electronic_output_dispatch_date.sql','88263ed13770f367d245b91a05661f1b4a455715fd9aa71fc1429d87e1d4822e','51f059492eb924cecaff0f427fe77d206ef8793c7ac6839605f61413ab5d00d3','shared-project-schema-v1');
  end if;
end;
$shared_compose_forward_1$;

-- The shared backend cannot bypass RLS. Limit access by the source's exact
-- table command grants plus a backend-only row policy on these two new tables.
drop policy if exists edoc_backend_numbering on edoc.official_document_number_counters;
create policy edoc_backend_numbering on edoc.official_document_number_counters
  to edoc_backend using (true) with check (true);
drop policy if exists edoc_backend_numbering on edoc.official_document_number_allocations;
create policy edoc_backend_numbering on edoc.official_document_number_allocations
  to edoc_backend using (true) with check (true);
revoke all on edoc.official_document_number_counters,edoc.official_document_number_allocations
  from public,anon,authenticated,service_role,authenticator;
revoke all on function edoc.edoc_number_safe_metadata(text),edoc.edoc_allocate_official_number(),
  edoc.edoc_record_official_number(),edoc.edoc_guard_official_number(),edoc.edoc_guard_number_allocation()
  from public,anon,authenticated,service_role,authenticator;
revoke all on function edoc_private.is_electronic_compose(edoc.official_documents),
  edoc_private.guard_compose_output_fields(),edoc_private.complete_electronic_compose(text,text)
  from public,anon,authenticated,service_role,authenticator;
-- Only the primitive, read-free composite predicate is needed by the invoker
-- guard; completion remains exclusively reachable through the approved RPC.
grant execute on function edoc_private.is_electronic_compose(edoc.official_documents) to edoc_backend;
revoke all on function edoc_private.complete_electronic_compose(text,text) from edoc_backend;
notify pgrst, 'reload schema';
commit;
