-- Generated by tools/editor_storage_paths_shared_forward.py; exact source hashes are locked.
-- Only editor path constraints and existing trigger functions change.
-- No document, asset, Storage object, identity, organization or grant is rewritten.
begin;
set local lock_timeout = '5s';
set local statement_timeout = '30s';
select pg_catalog.pg_advisory_xact_lock(1788103601, 20260913);
do $preflight$
begin
  if pg_catalog.to_regclass('edoc_private.shared_project_migration_ledger') is null
     or pg_catalog.to_regclass('edoc.official_document_editor_storage_jobs') is null
     or not exists(select 1 from pg_catalog.pg_roles where rolname='edoc_backend' and not rolbypassrls)
     or not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260827194500_promote_editor_tus_staging_to_immutable.sql')
     or not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260913060040_editor_cross_company_workflow_scope.sql') then
    raise exception 'shared_editor_storage_paths_preflight_failed';
  end if;
end $preflight$;
do $forward$
begin
  if exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260913130517_editor_storage_v2_opaque_paths.sql'
    and (source_sha256 <> '6591b15591f5598f62613afa3f4d400817ff780bb11ea9d272ba81a72ac92613' or transformed_sha256 <> '075ea8cc226632f9a49947d27d55f9e8512d4d470e54a1bbe36ab9e4fc9efeec')) then
    raise exception 'shared_editor_storage_paths_source_hash_mismatch';
  end if;
  if not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260913130517_editor_storage_v2_opaque_paths.sql') then
    if (select pg_catalog.md5(prosrc) from pg_catalog.pg_proc where oid='edoc.edoc_guard_editor_storage_job()'::regprocedure)
         is distinct from '4bbd8813129ea0468b744c1398dde366'
       or (select pg_catalog.md5(prosrc) from pg_catalog.pg_proc where oid='edoc.edoc_bind_finalized_editor_asset_storage()'::regprocedure)
         is distinct from 'f8ce237c4031eef0a257c1dbd436b753' then
      raise exception 'shared_editor_storage_paths_base_drift';
    end if;
    execute $source$
-- Keep original display names in metadata, not in new Storage object keys.
-- Match the Python v2 opaque-key contract at all database boundaries.
-- Forward-only: no source assets, committed keys, roles or RLS are changed.
-- V1 rows without storage_key_version retain their existing immutable paths.

alter table edoc.official_document_editor_storage_jobs
  drop constraint official_editor_storage_job_path_check;
alter table edoc.official_document_editor_storage_jobs
  add constraint official_editor_storage_job_path_check check (
    staging_bucket = 'edoc-private'
    and pg_catalog.btrim(staging_path) <> ''
    and final_bucket = 'edoc-private'
    and pg_catalog.btrim(final_path) <> ''
    and pg_catalog.btrim(token_expires_at) <> ''
    and token_expires_at ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}$'
    and pg_catalog.pg_input_is_valid(token_expires_at, 'timestamp without time zone')
    and staging_path <> final_path
    and (
      (
        pg_catalog.left(staging_path, pg_catalog.length('editor/' || document_id || '/' || asset_id || '-'))
          = 'editor/' || document_id || '/' || asset_id || '-'
        and pg_catalog.left(final_path, pg_catalog.length('editor-final/' || document_id || '/' || asset_id || '/' || pg_catalog.upper(expected_sha256) || '-'))
          = 'editor-final/' || document_id || '/' || asset_id || '/' || pg_catalog.upper(expected_sha256) || '-'
      )
      or (
        document_id ~ '^[A-Za-z0-9_-]{1,160}$'
        and asset_id ~ '^[A-Za-z0-9_-]{1,160}$'
        and (
          (staging_path = 'editor/' || document_id || '/' || asset_id || '.pdf'
           and final_path = 'editor-final/' || document_id || '/' || asset_id || '/' || pg_catalog.upper(expected_sha256) || '.pdf')
          or (staging_path = 'editor/' || document_id || '/' || asset_id || '.png'
           and final_path = 'editor-final/' || document_id || '/' || asset_id || '/' || pg_catalog.upper(expected_sha256) || '.png')
          or (staging_path = 'editor/' || document_id || '/' || asset_id || '.jpg'
           and final_path = 'editor-final/' || document_id || '/' || asset_id || '/' || pg_catalog.upper(expected_sha256) || '.jpg')
        )
      )
    )
  );

create or replace function edoc.edoc_guard_editor_storage_job()
returns trigger
language plpgsql
set search_path to ''
as $function$
declare
  v_asset edoc.official_document_editor_assets%rowtype;
  v_file edoc.file_objects%rowtype;
  v_expected_final_path text;
  v_expected_staging_path text;
  v_metadata jsonb;
  v_extension text;
begin
  if tg_op = 'INSERT' then
    select asset.*
    into v_asset
    from edoc.official_document_editor_assets asset
    where asset.id = new.asset_id;

    v_metadata := coalesce(nullif(v_asset.metadata_json::text, ''), '{}')::jsonb;
    if pg_catalog.jsonb_typeof(v_metadata) is distinct from 'object' then
      raise exception using errcode = '22023', message = 'editor_storage_key_version_invalid';
    end if;
    if v_metadata -> 'storage_key_version' = '2'::jsonb then
      v_extension := case v_asset.mime_type
        when 'application/pdf' then 'pdf'
        when 'image/png' then 'png'
        when 'image/jpeg' then 'jpg'
        else null end;
      if v_extension is null
         or new.document_id !~ '^[A-Za-z0-9_-]{1,160}$'
         or new.asset_id !~ '^[A-Za-z0-9_-]{1,160}$'
         or (v_asset.asset_kind in ('source_pdf', 'import_pdf') and v_extension <> 'pdf')
         or (v_asset.asset_kind = 'image' and v_extension not in ('png', 'jpg')) then
        raise exception using errcode = '22023', message = 'editor_storage_v2_identity_invalid';
      end if;
      v_expected_staging_path := 'editor/' || new.document_id || '/' || new.asset_id || '.' || v_extension;
      v_expected_final_path := 'editor-final/' || new.document_id || '/' || new.asset_id || '/' ||
        pg_catalog.upper(new.expected_sha256) || '.' || v_extension;
    elsif v_metadata ? 'storage_key_version' then
      raise exception using errcode = '22023', message = 'editor_storage_key_version_invalid';
    else
      -- Existing capabilities and committed objects keep their exact v1 keys.
      v_expected_staging_path := v_asset.storage_path;
      v_expected_final_path :=
        'editor-final/' || new.document_id || '/' || new.asset_id || '/' ||
        pg_catalog.upper(new.expected_sha256) || '-' ||
        pg_catalog.regexp_replace(v_asset.file_name, '^.*/', '');
    end if;
    if v_asset.id is null
       or v_asset.document_id is distinct from new.document_id
       or v_asset.asset_kind not in ('source_pdf', 'import_pdf', 'image')
       or v_asset.upload_status = 'finalized'
       or new.staging_bucket is distinct from 'edoc-private'
       or new.staging_bucket is distinct from v_asset.storage_bucket
       or new.staging_path is distinct from v_asset.storage_path
       or new.staging_path is distinct from v_expected_staging_path
       or new.final_bucket is distinct from 'edoc-private'
       or new.final_path is distinct from v_expected_final_path
       or pg_catalog.lower(new.expected_sha256)
            is distinct from pg_catalog.lower(v_asset.expected_sha256)
       or new.expected_size_bytes is distinct from v_asset.size_bytes
       or new.status is distinct from 'pending'
       or new.lease_token <> ''
       or new.lease_expires_at <> ''
       or new.final_file_object_id is not null
       or new.attempt_count <> 0
       or new.last_error_code <> ''
       or new.cleaned_at is not null then
      raise exception using
        errcode = '22023',
        message = 'editor_storage_job_binding_invalid';
    end if;
    return new;
  end if;

  -- Path, digest, object identity and capability expiry are append-only
  -- evidence. Cleanup may update only lifecycle fields.
  if new.id is distinct from old.id
     or new.asset_id is distinct from old.asset_id
     or new.document_id is distinct from old.document_id
     or new.staging_bucket is distinct from old.staging_bucket
     or new.staging_path is distinct from old.staging_path
     or new.final_bucket is distinct from old.final_bucket
     or new.final_path is distinct from old.final_path
     or new.expected_sha256 is distinct from old.expected_sha256
     or new.expected_size_bytes is distinct from old.expected_size_bytes
     or new.token_expires_at is distinct from old.token_expires_at
     or new.created_at is distinct from old.created_at
     or new.attempt_count < old.attempt_count
     or (old.final_file_object_id is not null
         and new.final_file_object_id is distinct from old.final_file_object_id) then
    raise exception using
      errcode = '55000',
      message = 'editor_storage_job_binding_immutable';
  end if;

  if old.final_file_object_id is null
     and new.final_file_object_id is not null
     and not (
       old.status = 'promoting'
       and new.status = 'committed'
       and pg_catalog.pg_trigger_depth() >= 2
     ) then
    raise exception using
      errcode = '55000',
      message = 'editor_storage_job_file_binding_forbidden';
  end if;

  if old.status = 'cleaned' and new is distinct from old then
    raise exception using
      errcode = '55000',
      message = 'editor_storage_job_cleaned_immutable';
  end if;

  if new.status in ('promoting', 'cleaning') then
    if (case
         when not pg_catalog.pg_input_is_valid(
           new.lease_expires_at,
           'timestamp without time zone'
         ) then true
         else new.lease_expires_at::timestamp <= pg_catalog.clock_timestamp()
       end)
       or (
         (
           old.status not in ('promoting', 'cleaning')
           or new.lease_token is distinct from old.lease_token
           or new.status is distinct from old.status
         )
         and new.attempt_count <= old.attempt_count
       ) then
      raise exception using
        errcode = '22023',
        message = 'editor_storage_job_lease_invalid';
    end if;
  end if;

  if old.status in ('promoting', 'cleaning')
     and old.lease_token <> ''
     and old.lease_expires_at::timestamp > pg_catalog.clock_timestamp()
     and new.status in ('promoting', 'cleaning')
     and (
       new.lease_token is distinct from old.lease_token
       or new.status is distinct from old.status
     ) then
    raise exception using
      errcode = '55000',
      message = 'editor_storage_job_lease_active';
  end if;

  if new.status = 'committed' then
    if old.status is distinct from 'promoting'
       or pg_catalog.pg_trigger_depth() < 2
       or new.final_file_object_id is null
       or old.lease_token = ''
       or not pg_catalog.pg_input_is_valid(
            old.lease_expires_at,
            'timestamp without time zone'
          )
       or old.lease_expires_at::timestamp < pg_catalog.clock_timestamp()
       or new.lease_token <> ''
       or new.lease_expires_at <> '' then
      raise exception using
        errcode = '55000',
        message = 'editor_storage_job_commit_forbidden';
    end if;
    select file_object.*
    into v_file
    from edoc.file_objects file_object
    where file_object.id = new.final_file_object_id;
    if v_file.id is null
       or v_file.document_id is distinct from new.document_id
       or v_file.bucket is distinct from new.final_bucket
       or v_file.storage_key is distinct from new.final_path
       or pg_catalog.lower(v_file.sha256)
            is distinct from pg_catalog.lower(new.expected_sha256)
       or v_file.size_bytes is distinct from new.expected_size_bytes
       or v_file.storage_provider is distinct from 'supabase' then
      raise exception using
        errcode = '22023',
        message = 'editor_storage_job_commit_invalid';
    end if;
  elsif old.status = 'pending'
        and new.status not in ('pending', 'promoting', 'cleaning') then
    raise exception using
      errcode = '55000',
      message = 'editor_storage_job_transition_invalid';
  elsif old.status = 'promoting'
        and new.status not in ('promoting', 'pending', 'committed', 'cleaning') then
    raise exception using
      errcode = '55000',
      message = 'editor_storage_job_transition_invalid';
  elsif old.status = 'committed'
        and new.status not in ('committed', 'cleaning') then
    raise exception using
      errcode = '55000',
      message = 'editor_storage_job_transition_invalid';
  elsif old.status = 'cleanup_failed'
        and new.status not in ('cleanup_failed', 'cleaning') then
    raise exception using
      errcode = '55000',
      message = 'editor_storage_job_transition_invalid';
  elsif old.status = 'cleaning'
        and new.status not in ('cleaning', 'cleaned', 'cleanup_failed') then
    raise exception using
      errcode = '55000',
      message = 'editor_storage_job_transition_invalid';
  end if;

  if new.status = 'cleaned' and new.cleaned_at is null then
    raise exception using
      errcode = '22023',
      message = 'editor_storage_job_cleaned_at_required';
  end if;
  return new;
end;
$function$;

alter function edoc.edoc_guard_editor_storage_job() owner to postgres;
revoke all on function edoc.edoc_guard_editor_storage_job()
from public, anon, authenticated;

drop trigger if exists trg_edoc_guard_editor_storage_job
on edoc.official_document_editor_storage_jobs;

create trigger trg_edoc_guard_editor_storage_job
before insert or update
on edoc.official_document_editor_storage_jobs
for each row
execute function edoc.edoc_guard_editor_storage_job();

create or replace function edoc.edoc_bind_finalized_editor_asset_storage()
returns trigger
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_file edoc.file_objects%rowtype;
  v_job edoc.official_document_editor_storage_jobs%rowtype;
  v_expected_path text;
  v_metadata jsonb;
  v_extension text;
begin
  if tg_op = 'DELETE' then
    if old.asset_kind in ('source_pdf', 'import_pdf', 'image')
       and old.upload_status = 'finalized' then
      raise exception using
        errcode = '55000',
        message = 'editor_finalized_asset_immutable';
    end if;
    return old;
  end if;

  -- Once finalized, every field is immutable. This also prevents a stale
  -- failure request from downgrading a successful concurrent finalize.
  if tg_op = 'UPDATE'
     and old.asset_kind in ('source_pdf', 'import_pdf', 'image')
     and old.upload_status = 'finalized' then
    if new is distinct from old then
      raise exception using
        errcode = '55000',
        message = 'editor_finalized_asset_immutable';
    end if;
    return new;
  end if;

  if new.asset_kind not in ('source_pdf', 'import_pdf', 'image')
     or new.upload_status is distinct from 'finalized' then
    return new;
  end if;

  if new.file_object_id is null
     or new.sha256 !~ '^[A-Fa-f0-9]{64}$'
     or new.size_bytes <= 0 then
    raise exception using
      errcode = '22023',
      message = 'editor_immutable_file_object_required';
  end if;

  -- Browser-uploaded source assets are always created as pending first so a
  -- lifecycle job exists before bytes can be promoted. A direct finalized
  -- insert bypasses that invariant and is rejected.
  if tg_op <> 'UPDATE' then
    raise exception using
      errcode = '22023',
      message = 'editor_finalized_asset_insert_forbidden';
  end if;

  select file_object.*
  into v_file
  from edoc.file_objects file_object
  where file_object.id = new.file_object_id;

  select storage_job.*
  into v_job
  from edoc.official_document_editor_storage_jobs storage_job
  where storage_job.asset_id = new.id
    and storage_job.document_id = new.document_id
  for update;

  v_metadata := coalesce(nullif(old.metadata_json::text, ''), '{}')::jsonb;
  if pg_catalog.jsonb_typeof(v_metadata) is distinct from 'object'
     or (coalesce(nullif(new.metadata_json::text, ''), '{}')::jsonb -> 'storage_key_version')
        is distinct from (v_metadata -> 'storage_key_version')
     or new.id is distinct from old.id
     or new.document_id is distinct from old.document_id
     or new.asset_kind is distinct from old.asset_kind
     or new.mime_type is distinct from old.mime_type
     or new.file_name is distinct from old.file_name then
    raise exception using errcode = '22023', message = 'editor_storage_key_version_invalid';
  end if;
  if v_metadata -> 'storage_key_version' = '2'::jsonb then
    v_extension := case new.mime_type
      when 'application/pdf' then 'pdf'
      when 'image/png' then 'png'
      when 'image/jpeg' then 'jpg'
      else null end;
    if v_extension is null
       or new.document_id !~ '^[A-Za-z0-9_-]{1,160}$'
       or new.id !~ '^[A-Za-z0-9_-]{1,160}$'
       or (new.asset_kind in ('source_pdf', 'import_pdf') and v_extension <> 'pdf')
       or (new.asset_kind = 'image' and v_extension not in ('png', 'jpg'))
       or old.storage_path is distinct from
         'editor/' || new.document_id || '/' || new.id || '.' || v_extension then
      raise exception using errcode = '22023', message = 'editor_storage_v2_identity_invalid';
    end if;
    v_expected_path := 'editor-final/' || new.document_id || '/' || new.id || '/' ||
      pg_catalog.upper(new.sha256) || '.' || v_extension;
  elsif v_metadata ? 'storage_key_version' then
    raise exception using errcode = '22023', message = 'editor_storage_key_version_invalid';
  else
    v_expected_path := 'editor-final/' || new.document_id || '/' || new.id || '/' ||
      pg_catalog.upper(new.sha256) || '-' ||
      pg_catalog.regexp_replace(new.file_name, '^.*/', '');
  end if;
  if v_file.id is null
     or v_job.id is null
     or v_job.status is distinct from 'promoting'
     or v_job.lease_token = ''
     or not pg_catalog.pg_input_is_valid(
          v_job.lease_expires_at,
          'timestamp without time zone'
        )
     or v_job.lease_expires_at::timestamp < pg_catalog.clock_timestamp()
     or v_file.document_id is distinct from new.document_id
     or v_file.bucket is distinct from 'edoc-private'
     or v_file.storage_provider is distinct from 'supabase'
     or v_file.storage_key is distinct from v_expected_path
     or pg_catalog.lower(v_file.sha256) is distinct from pg_catalog.lower(new.sha256)
     or v_file.size_bytes is distinct from new.size_bytes
     or v_job.staging_bucket is distinct from old.storage_bucket
     or v_job.staging_path is distinct from old.storage_path
     or v_job.final_bucket is distinct from v_file.bucket
     or v_job.final_path is distinct from v_file.storage_key
     or pg_catalog.lower(v_job.expected_sha256) is distinct from pg_catalog.lower(new.sha256)
     or pg_catalog.lower(new.expected_sha256) is distinct from pg_catalog.lower(new.sha256)
     or v_job.expected_size_bytes is distinct from new.size_bytes then
    raise exception using
      errcode = '22023',
      message = 'editor_immutable_storage_required';
  end if;

  new.storage_bucket := v_file.bucket;
  new.storage_path := v_file.storage_key;
  update edoc.official_document_editor_storage_jobs
  set status = 'committed',
      lease_token = '',
      lease_expires_at = '',
      final_file_object_id = v_file.id,
      last_error_code = '',
      updated_at = pg_catalog.to_char(pg_catalog.now(), 'YYYY-MM-DD HH24:MI:SS')
  where id = v_job.id;
  return new;
end;
$function$;

alter function edoc.edoc_bind_finalized_editor_asset_storage() owner to postgres;
revoke all on function edoc.edoc_bind_finalized_editor_asset_storage()

from public, anon, authenticated;
$source$;
    insert into edoc_private.shared_project_migration_ledger(file_name,source_sha256,transformed_sha256,bundle_version)
      values('20260913130517_editor_storage_v2_opaque_paths.sql','6591b15591f5598f62613afa3f4d400817ff780bb11ea9d272ba81a72ac92613','075ea8cc226632f9a49947d27d55f9e8512d4d470e54a1bbe36ab9e4fc9efeec','shared-project-schema-v1');
  end if;
end $forward$;
notify pgrst, 'reload schema';
commit;
