-- Generated by tools/dispatch_generation_shared_forward.py.
-- Function lookup guards only; immutable prior workflows are not changed.
begin;
select pg_catalog.pg_advisory_xact_lock(1788103601, 20260924);
do $dispatch_generation_forward$
begin
  if pg_catalog.to_regclass('edoc_private.shared_project_migration_ledger') is null
     or pg_catalog.to_regclass('edoc.official_documents') is null
     or not exists(select 1 from pg_catalog.pg_roles where rolname='edoc_backend' and not rolbypassrls)
     or not exists(select 1 from edoc_private.shared_project_migration_ledger
       where file_name='20260922074613_configurable_official_workflows.sql') then
    raise exception 'shared_dispatch_generation_preflight_failed';
  end if;
  if exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260924155456_latest_generation_dispatch_owner.sql'
    and (source_sha256 is distinct from '4a8dac60a35227e3a4cbff51b65db2f3d1e0be7c6bd7a67c454cacf88652c522' or transformed_sha256 is distinct from '7b6134e2cec6199c7018d3d29cb777c812043646b56ed925821c8ecea5180c0a')) then
    raise exception 'shared_dispatch_generation_source_hash_mismatch';
  end if;
  if not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260924155456_latest_generation_dispatch_owner.sql') then
    execute $dispatch_generation_source$
-- Preserve each deployed function's current authorization, lock, and output
-- guards. Narrow only its GA lookup to the latest immutable workflow generation.
do $latest_dispatch_generation$
declare
  v_signature text;
  v_definition text;
  v_old text := $old$and step.step_key = 'general_affairs_review'
       and step.status = 'approved'$old$;
  v_new text := $new$and step.step_key = 'general_affairs_review'
       and step.workflow_generation = (
         select max(current_generation.workflow_generation)
         from edoc.official_document_approval_steps current_generation
         where current_generation.document_id = v_document.id
       )
       and step.status = 'approved'$new$;
begin
  foreach v_signature in array array[
    'edoc.edoc_create_official_document_dispatch_record(text,text)',
    'edoc.edoc_complete_official_document_stamp(text,text,text,text)'
  ] loop
    v_definition := pg_catalog.pg_get_functiondef(pg_catalog.to_regprocedure(v_signature));
    if v_definition is null then
      raise exception 'official_dispatch_generation_rpc_missing: %',v_signature;
    end if;
    if pg_catalog.strpos(v_definition,v_new)>0 then
      continue;
    end if;
    if pg_catalog.length(v_definition)-pg_catalog.length(pg_catalog.replace(v_definition,v_old,'')) <> pg_catalog.length(v_old) then
      raise exception 'official_dispatch_generation_rpc_source_drift: %',v_signature;
    end if;
    execute pg_catalog.replace(v_definition,v_old,v_new);
  end loop;
end $latest_dispatch_generation$;
$dispatch_generation_source$;
    insert into edoc_private.shared_project_migration_ledger(file_name,source_sha256,transformed_sha256,bundle_version)
      values('20260924155456_latest_generation_dispatch_owner.sql','4a8dac60a35227e3a4cbff51b65db2f3d1e0be7c6bd7a67c454cacf88652c522','7b6134e2cec6199c7018d3d29cb777c812043646b56ed925821c8ecea5180c0a','shared-project-schema-v1');
  end if;
end $dispatch_generation_forward$;
notify pgrst,'reload schema';
commit;
