"""Deterministic shared-schema forward for the frozen compose source deltas."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from tools.shared_supabase_bootstrap import ROOT, BUNDLE_VERSION, sha256_text, transform_sql

SOURCES = (
    "20260908135730_immutable_official_document_numbering.sql",
    "20260908135911_compose_electronic_output_dispatch_date.sql",
)
FORWARD_NAME = "20260908142137_shared_compose_numbering_and_output.sql"


def render_shared_forward() -> str:
    chunks = ["""-- Generated by tools/compose_shared_forward.py from the frozen source deltas.
-- One transaction; no public HR tables, real exchange provider, or file bytes.
begin;
select pg_catalog.pg_advisory_xact_lock(1788103601, 20260908);
do $shared_compose_preflight$
begin
  if pg_catalog.to_regclass('edoc_private.shared_project_migration_ledger') is null
     or pg_catalog.to_regclass('edoc.official_documents') is null
     or not exists (select 1 from pg_catalog.pg_roles where rolname='edoc_backend' and not rolbypassrls)
     or not exists (select 1 from edoc_private.shared_project_migration_ledger
       where file_name='20260827050450_atomic_official_submission_editor_finalize_forward.sql')
     or not exists (select 1 from edoc_private.shared_project_migration_ledger
       where file_name='20260827133545_fix_official_document_function_type_resolution.sql') then
    raise exception 'shared_compose_preflight_failed';
  end if;
end;
$shared_compose_preflight$;
"""]
    for index, name in enumerate(SOURCES):
        source = (ROOT / "supabase/migrations" / name).read_text()
        transformed = transform_sql(source)
        source_hash, transformed_hash = sha256_text(source), sha256_text(transformed)
        tag = f"shared_compose_source_{index}"
        chunks.append(f"""
do $shared_compose_forward_{index}$
begin
  if exists (select 1 from edoc_private.shared_project_migration_ledger
    where file_name='{name}' and
      (source_sha256 <> '{source_hash}' or transformed_sha256 <> '{transformed_hash}')) then
    raise exception 'shared_compose_source_hash_mismatch';
  end if;
  if not exists (select 1 from edoc_private.shared_project_migration_ledger where file_name='{name}') then
    execute ${tag}$
{transformed}${tag}$;
    insert into edoc_private.shared_project_migration_ledger
      (file_name,source_sha256,transformed_sha256,bundle_version)
    values ('{name}','{source_hash}','{transformed_hash}','{BUNDLE_VERSION}');
  end if;
end;
$shared_compose_forward_{index}$;
""")
    chunks.append("""
-- The shared backend cannot bypass RLS. Limit access by the source's exact
-- table command grants plus a backend-only row policy on these two new tables.
drop policy if exists edoc_backend_numbering on edoc.official_document_number_counters;
create policy edoc_backend_numbering on edoc.official_document_number_counters
  to edoc_backend using (true) with check (true);
drop policy if exists edoc_backend_numbering on edoc.official_document_number_allocations;
create policy edoc_backend_numbering on edoc.official_document_number_allocations
  to edoc_backend using (true) with check (true);
revoke all on edoc.official_document_number_counters,edoc.official_document_number_allocations
  from public,anon,authenticated,service_role,authenticator;
revoke all on function edoc.edoc_number_safe_metadata(text),edoc.edoc_allocate_official_number(),
  edoc.edoc_record_official_number(),edoc.edoc_guard_official_number(),edoc.edoc_guard_number_allocation()
  from public,anon,authenticated,service_role,authenticator;
revoke all on function edoc_private.is_electronic_compose(edoc.official_documents),
  edoc_private.guard_compose_output_fields(),edoc_private.complete_electronic_compose(text,text)
  from public,anon,authenticated,service_role,authenticator;
-- Only the primitive, read-free composite predicate is needed by the invoker
-- guard; completion remains exclusively reachable through the approved RPC.
grant execute on function edoc_private.is_electronic_compose(edoc.official_documents) to edoc_backend;
revoke all on function edoc_private.complete_electronic_compose(text,text) from edoc_backend;
notify pgrst, 'reload schema';
commit;
""")
    return "".join(chunks)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Verify committed forward matches source SQL without writing files")
    args = parser.parse_args()
    rendered = render_shared_forward()
    if args.check:
        target = ROOT / "supabase/shared-project-migrations" / FORWARD_NAME
        matches = target.is_file() and target.read_text() == rendered
        print(json.dumps({"matches": matches, "file": FORWARD_NAME}))
        raise SystemExit(0 if matches else 1)
    print(rendered, end="")
