"""Deterministic private-schema forward for the approved compose/editor repair."""
import argparse
import json
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from tools.shared_supabase_bootstrap import ROOT, BUNDLE_VERSION, sha256_text, transform_sql

SOURCES = ("20260911133144_compose_resilience_drafts_revision.sql", "20260911133603_editor_conflict_copy_atomic.sql")
FORWARD_NAME = "20260911135434_shared_compose_editor_resilience.sql"

def render_shared_forward():
    chunks = ["""-- Generated by tools/compose_editor_shared_forward.py; source hashes are locked.
-- Only the isolated edoc namespace changes. Do not send official exchanges.
begin;
select pg_catalog.pg_advisory_xact_lock(1788103601, 20260911);
do $preflight$
begin
  if pg_catalog.to_regclass('edoc_private.shared_project_migration_ledger') is null
     or pg_catalog.to_regclass('edoc.official_documents') is null
     or not exists(select 1 from pg_catalog.pg_roles where rolname='edoc_backend' and not rolbypassrls)
     or not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260908135911_compose_electronic_output_dispatch_date.sql') then
    raise exception 'shared_compose_editor_preflight_failed';
  end if;
end $preflight$;
"""]
    for i, name in enumerate(SOURCES):
        source = (ROOT / "supabase/migrations" / name).read_text()
        transformed = transform_sql(source)
        a, b = sha256_text(source), sha256_text(transformed)
        chunks.append(f"""
do $forward_{i}$
begin
  if exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='{name}'
    and (source_sha256 <> '{a}' or transformed_sha256 <> '{b}')) then
    raise exception 'shared_compose_editor_source_hash_mismatch';
  end if;
  if not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='{name}') then
    execute $source_{i}$
{transformed}$source_{i}$;
    insert into edoc_private.shared_project_migration_ledger(file_name,source_sha256,transformed_sha256,bundle_version)
      values('{name}','{a}','{b}','{BUNDLE_VERSION}');
  end if;
end $forward_{i}$;
""")
    chunks.append("""
-- The dedicated backend has no BYPASSRLS; permit rows only to that backend.
drop policy if exists edoc_backend_compose_drafts on edoc.official_document_compose_drafts;
create policy edoc_backend_compose_drafts on edoc.official_document_compose_drafts
  to edoc_backend using(true) with check(true);
revoke all on edoc.official_document_compose_drafts from public,anon,authenticated,service_role,authenticator;
revoke all on function edoc.edoc_save_compose_draft(text,text,text,integer,jsonb,text,boolean),
  edoc.edoc_copy_editor_conflict(jsonb) from public,anon,authenticated,service_role,authenticator;
notify pgrst, 'reload schema';
commit;
""")
    return "".join(chunks)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(); parser.add_argument("--check", action="store_true")
    args = parser.parse_args(); rendered = render_shared_forward()
    if args.check:
        target = ROOT / "supabase/shared-project-migrations" / FORWARD_NAME
        matches = target.is_file() and target.read_text() == rendered
        print(json.dumps({"matches": matches, "file": FORWARD_NAME}))
        raise SystemExit(0 if matches else 1)
    print(rendered, end="")
