"""Deterministic shared-schema forward for generation-bound dispatch ownership."""
import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from tools.shared_supabase_bootstrap import ROOT, BUNDLE_VERSION, sha256_text, transform_sql

SOURCE = "20260924155456_latest_generation_dispatch_owner.sql"
FORWARD_NAME = "20260924155457_shared_latest_generation_dispatch_owner.sql"


def render_shared_forward():
    source = (ROOT / "supabase/migrations" / SOURCE).read_text()
    transformed = transform_sql(source)
    source_hash, transformed_hash = sha256_text(source), sha256_text(transformed)
    return f"""-- Generated by tools/dispatch_generation_shared_forward.py.
-- Function lookup guards only; immutable prior workflows are not changed.
begin;
select pg_catalog.pg_advisory_xact_lock(1788103601, 20260924);
do $dispatch_generation_forward$
begin
  if pg_catalog.to_regclass('edoc_private.shared_project_migration_ledger') is null
     or pg_catalog.to_regclass('edoc.official_documents') is null
     or not exists(select 1 from pg_catalog.pg_roles where rolname='edoc_backend' and not rolbypassrls)
     or not exists(select 1 from edoc_private.shared_project_migration_ledger
       where file_name='20260922074613_configurable_official_workflows.sql') then
    raise exception 'shared_dispatch_generation_preflight_failed';
  end if;
  if exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='{SOURCE}'
    and (source_sha256 is distinct from '{source_hash}' or transformed_sha256 is distinct from '{transformed_hash}')) then
    raise exception 'shared_dispatch_generation_source_hash_mismatch';
  end if;
  if not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='{SOURCE}') then
    execute $dispatch_generation_source$
{transformed}$dispatch_generation_source$;
    insert into edoc_private.shared_project_migration_ledger(file_name,source_sha256,transformed_sha256,bundle_version)
      values('{SOURCE}','{source_hash}','{transformed_hash}','{BUNDLE_VERSION}');
  end if;
end $dispatch_generation_forward$;
notify pgrst,'reload schema';
commit;
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_shared_forward()
    if args.check:
        target = ROOT / "supabase/shared-project-migrations" / FORWARD_NAME
        matches = target.is_file() and target.read_text() == rendered
        print(json.dumps({"matches": matches, "file": FORWARD_NAME}))
        raise SystemExit(0 if matches else 1)
    print(rendered, end="")
