"""Bounded private-schema forward for V2 selectable applicant company/unit."""
import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from tools.shared_supabase_bootstrap import ROOT, BUNDLE_VERSION, sha256_text, transform_sql

SOURCES = (
    "20260913055452_editor_applicant_selection_scope.sql",
    "20260913060040_editor_cross_company_workflow_scope.sql",
)
FORWARD_NAME = "20260913061206_shared_editor_applicant_selection.sql"


def render_shared_forward():
    chunks = ["""-- Generated by tools/editor_applicant_shared_forward.py; source hashes are locked.
-- Only two V2 application/workflow forwards in the private edoc namespace.
-- No source assets, Finance organization rows, user identities or grants change.
begin;
select pg_catalog.pg_advisory_xact_lock(1788103601, 20260913);
do $preflight$
begin
  if pg_catalog.to_regclass('edoc_private.shared_project_migration_ledger') is null
     or pg_catalog.to_regclass('edoc.official_documents') is null
     or not exists(select 1 from pg_catalog.pg_roles where rolname='edoc_backend' and not rolbypassrls)
     or not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260911133144_compose_resilience_drafts_revision.sql')
     or not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260911133603_editor_conflict_copy_atomic.sql') then
    raise exception 'shared_editor_applicant_preflight_failed';
  end if;
end $preflight$;
"""]
    for index, name in enumerate(SOURCES):
        source = (ROOT / "supabase/migrations" / name).read_text()
        transformed = transform_sql(source)
        source_hash, transformed_hash = sha256_text(source), sha256_text(transformed)
        chunks.append(f"""
do $forward_{index}$
begin
  if exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='{name}'
    and (source_sha256 <> '{source_hash}' or transformed_sha256 <> '{transformed_hash}')) then
    raise exception 'shared_editor_applicant_source_hash_mismatch';
  end if;
  if not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='{name}') then
    execute $source_{index}$
{transformed}$source_{index}$;
    insert into edoc_private.shared_project_migration_ledger(file_name,source_sha256,transformed_sha256,bundle_version)
      values('{name}','{source_hash}','{transformed_hash}','{BUNDLE_VERSION}');
  end if;
end $forward_{index}$;
""")
    chunks.append("""
notify pgrst, 'reload schema';
commit;
""")
    return "".join(chunks)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_shared_forward()
    if args.check:
        target = ROOT / "supabase/shared-project-migrations" / FORWARD_NAME
        matches = target.is_file() and target.read_text() == rendered
        print(json.dumps({"matches": matches, "file": FORWARD_NAME}))
        raise SystemExit(0 if matches else 1)
    print(rendered, end="")
