"""Bounded private-schema forward for versioned editor Storage paths."""
import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from tools.shared_supabase_bootstrap import ROOT, BUNDLE_VERSION, sha256_text, transform_sql

SOURCE = "20260913130517_editor_storage_v2_opaque_paths.sql"
FORWARD_NAME = "20260913130517_shared_editor_storage_v2_opaque_paths.sql"


def render_shared_forward():
    source = (ROOT / "supabase/migrations" / SOURCE).read_text()
    transformed = transform_sql(source)
    source_hash, transformed_hash = sha256_text(source), sha256_text(transformed)
    return f"""-- Generated by tools/editor_storage_paths_shared_forward.py; exact source hashes are locked.
-- Only editor path constraints and existing trigger functions change.
-- No document, asset, Storage object, identity, organization or grant is rewritten.
begin;
set local lock_timeout = '5s';
set local statement_timeout = '30s';
select pg_catalog.pg_advisory_xact_lock(1788103601, 20260913);
do $preflight$
begin
  if pg_catalog.to_regclass('edoc_private.shared_project_migration_ledger') is null
     or pg_catalog.to_regclass('edoc.official_document_editor_storage_jobs') is null
     or not exists(select 1 from pg_catalog.pg_roles where rolname='edoc_backend' and not rolbypassrls)
     or not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260827194500_promote_editor_tus_staging_to_immutable.sql')
     or not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='20260913060040_editor_cross_company_workflow_scope.sql') then
    raise exception 'shared_editor_storage_paths_preflight_failed';
  end if;
end $preflight$;
do $forward$
begin
  if exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='{SOURCE}'
    and (source_sha256 <> '{source_hash}' or transformed_sha256 <> '{transformed_hash}')) then
    raise exception 'shared_editor_storage_paths_source_hash_mismatch';
  end if;
  if not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='{SOURCE}') then
    if (select pg_catalog.md5(prosrc) from pg_catalog.pg_proc where oid='edoc.edoc_guard_editor_storage_job()'::regprocedure)
         is distinct from '4bbd8813129ea0468b744c1398dde366'
       or (select pg_catalog.md5(prosrc) from pg_catalog.pg_proc where oid='edoc.edoc_bind_finalized_editor_asset_storage()'::regprocedure)
         is distinct from 'f8ce237c4031eef0a257c1dbd436b753' then
      raise exception 'shared_editor_storage_paths_base_drift';
    end if;
    execute $source$
{transformed}$source$;
    insert into edoc_private.shared_project_migration_ledger(file_name,source_sha256,transformed_sha256,bundle_version)
      values('{SOURCE}','{source_hash}','{transformed_hash}','{BUNDLE_VERSION}');
  end if;
end $forward$;
notify pgrst, 'reload schema';
commit;
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_shared_forward()
    if args.check:
        target = ROOT / "supabase/shared-project-migrations" / FORWARD_NAME
        matches = target.is_file() and target.read_text() == rendered
        print(json.dumps({"matches": matches, "file": FORWARD_NAME}))
        raise SystemExit(0 if matches else 1)
    print(rendered, end="")
