"""Bounded, deterministic terminal-decision DDL for the shared EDOC schema."""
import argparse
from tools.shared_supabase_bootstrap import ROOT, BUNDLE_VERSION, sha256_text, transform_sql

SOURCE = "20261006154028_terminal_official_decline.sql"
FORWARD_NAME = "20261006154029_shared_terminal_official_decline.sql"


def render_shared_forward():
    source = (ROOT / "supabase/migrations" / SOURCE).read_text()
    transformed = transform_sql(source)
    return f"""-- Generated by tools/terminal_decline_shared_forward.py; no Finance writes.
begin;
select pg_catalog.pg_advisory_xact_lock(1788103601, 20261006);
do $decline_forward$
begin
  if pg_catalog.to_regclass('edoc_private.shared_project_migration_ledger') is null
     or pg_catalog.to_regclass('edoc.official_documents') is null
     or not exists(select 1 from pg_catalog.pg_roles where rolname='edoc_backend' and not rolbypassrls)
     or not exists(select 1 from edoc_private.shared_project_migration_ledger
       where file_name='20260922074613_configurable_official_workflows.sql') then
    raise exception 'shared_terminal_decline_preflight_failed';
  end if;
  if exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='{SOURCE}'
    and (source_sha256 is distinct from '{sha256_text(source)}' or transformed_sha256 is distinct from '{sha256_text(transformed)}')) then
    raise exception 'shared_terminal_decline_source_hash_mismatch';
  end if;
  if not exists(select 1 from edoc_private.shared_project_migration_ledger where file_name='{SOURCE}') then
    execute $decline_source$
{transformed}$decline_source$;
    insert into edoc_private.shared_project_migration_ledger(file_name,source_sha256,transformed_sha256,bundle_version)
      values('{SOURCE}','{sha256_text(source)}','{sha256_text(transformed)}','{BUNDLE_VERSION}');
  end if;
end $decline_forward$;
notify pgrst,'reload schema';
commit;
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "supabase/shared-project-migrations" / FORWARD_NAME
    output = render_shared_forward()
    if args.write:
        target.write_text(output)
    elif args.check:
        raise SystemExit(0 if target.is_file() and target.read_text() == output else 1)
    else:
        print(output, end="")
